//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_Gallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OrderDetail
    {
        public int OrderDetail_Id { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<int> Art_Id { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    
        public virtual Tbl_Art Tbl_Art { get; set; }
        public virtual Tbl_Order Tbl_Order { get; set; }
    }
}
