//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_Gallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Report
    {
        public int R_Id { get; set; }
        public string R_Name { get; set; }
        public string R_Phone { get; set; }
        public string R_Email { get; set; }
        public string R_Subject { get; set; }
        public string R_File { get; set; }
        public string R_Dsc { get; set; }
    }
}
