//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_Gallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CAR
    {
        public int CAR_Id { get; set; }
        public string CAR_UserName { get; set; }
        public string CAR_FullName { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public string Artist_Name { get; set; }
        public string CAR_Image { get; set; }
        public string CAR_Desc { get; set; }
        public string CAR_Email { get; set; }
        public string CAR_Phone { get; set; }
        public Nullable<int> Artist_Id { get; set; }
    
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
