//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_Gallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_User()
        {
            this.Tbl_Wishlist = new HashSet<Tbl_Wishlist>();
            this.Tbl_Cart = new HashSet<Tbl_Cart>();
            this.Tbl_UserRole = new HashSet<Tbl_UserRole>();
            this.Tbl_CAR = new HashSet<Tbl_CAR>();
            this.Tbl_Art = new HashSet<Tbl_Art>();
        }
    
        public int User_Id { get; set; }
        public string User_Email { get; set; }
        public string User_Phone { get; set; }
        public string User_Password { get; set; }
        public string User_Image { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserName { get; set; }
        public string User_FirstName { get; set; }
        public string User_LastName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Wishlist> Tbl_Wishlist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Cart> Tbl_Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UserRole> Tbl_UserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_CAR> Tbl_CAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Art> Tbl_Art { get; set; }
    }
}
