//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_Gallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Order()
        {
            this.Tbl_OrderDetail = new HashSet<Tbl_OrderDetail>();
        }
    
        public int Order_Id { get; set; }
        public string Order_Username { get; set; }
        public string Order_FirstName { get; set; }
        public string Order_LastName { get; set; }
        public string Order_Address { get; set; }
        public string Order_City { get; set; }
        public string Order_State { get; set; }
        public string Order_PostalCode { get; set; }
        public string Order_Country { get; set; }
        public string Order_Phone { get; set; }
        public string Order_Email { get; set; }
        public Nullable<decimal> Order_Total { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<int> ItemCount { get; set; }
        public string PaymentType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OrderDetail> Tbl_OrderDetail { get; set; }
    }
}
