//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_Gallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Feedback
    {
        public int F_Id { get; set; }
        public string F_Type { get; set; }
        public string F_DYF { get; set; }
        public string F_FirstName { get; set; }
        public string F_LastName { get; set; }
        public string F_Phone { get; set; }
        public string F_Email { get; set; }
        public string F_UserName { get; set; }
    }
}
